### ISSUE TITLE
Suggestion: Risen

### ISSUE THREAD

**Issue by 8dcc** [ShaneMcC/beeps#20]
Could you please add the [TempleOS hymn](https://github.com/cia-foundation/TempleOS/blob/c26482bb6ad3f80106d28504ec5db3c6a360732c/Demo/AcctExample/TOS/TOSTheme.HC), risen? It would be amazing.

[Here](https://www.youtube.com/watch?v=LDvIeA5De4c) is a link that might be useful if you want to have a look.

**Comment by ShaneMcC** [comment]
I'm happy to accept a PR that adds it.
